# Generated by Django 3.1.4 on 2020-12-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_padi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_padi',
            new_name='is_paid',
        ),
    ]
